name: native_ar_viewer_example
description: Demonstrates how to use the native_ar_viewer plugin for Android.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  native_ar_viewer:
    path: ../

  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.8.3
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
